# Simulação de um banco de dados de produtos
produtos = [
    {"id": 1, "name": "skol 350ml", "price": 6, "category": "cerveja lata"},
    {"id": 2, "name": "skol 269ml", "price": 5, "category": "cerveja lata"},
    {"id": 3, "name": "itaipava 350ml", "price": 5, "category": "cerveja lata"},
    {"id": 4, "name": "petra", "price": 5, "category": "cerveja lata"},
    {"id": 5, "name": "amstel 269ml", "price": 5, "category": "cerveja lata"},
    {"id": 6, "name": "amstel 350ml", "price": 5, "category": "cerveja lata"},
    {"id": 7, "name": "original 269ml", "price": 5, "category": "cerveja lata"},
    {"id": 8, "name": "original 350ml", "price": 6, "category": "cerveja lata"},
    {"id": 9, "name": "brahma duplo malte 350ML", "price": 6, "category": "cerveja lata"},
    {"id": 10, "name": "heineken 269ml", "price": 5, "category": "cerveja lata"},
    {"id": 11, "name": "heineken 350ml", "price": 5, "category": "cerveja lata"},
    # ---------------------------------------------
    {"id": 12, "name": "suco dell vale lata", "price": 6, "category": "não alcolico"},
    {"id": 13, "name": "refrigerante 200 ml", "price": 3, "category": "não alcolico"},
    {"id": 14, "name": "refrigerante lata", "price": 6, "category": "não alcolico"},
    {"id": 15, "name": "energetico monster", "price": 14, "category": "não alcolico"},
    {"id": 16, "name": "energetico red bull", "price": 13, "category": "não alcolico"},
    {"id": 17, "name": "energetico volts 2 litros", "price": 15, "category": "não alcolico"},
    {"id": 18, "name": "agua sem gas", "price": 3, "category": "não alcolico"},
    {"id": 19, "name": "agua com gas", "price": 4, "category": "não alcolico"},
    {"id": 20, "name": "gatorade", "price": 9, "category": "não alcolico"},
    {"id": 21, "name": "refrigerante coca cola 2 lt", "price": 16, "category": "não alcolico"},
    {"id": 22, "name": "refrigerante fanta laranja 2 lt", "price": 13, "category": "não alcolico"},
    {"id": 23, "name": "refrigerante kuat 2 lt", "price": 10, "category": "não alcolico"},
    {"id": 24, "name": "refrigerante sprite 2 lt", "price": 13, "category": "não alcolico"},
    {"id": 25, "name": "refrigerante coca cola 1 lt", "price": 10, "category": "não alcolico"},
    {"id": 26, "name": "red bull 250ml", "price": 13, "category": "não alcolico"},
    # ---------------------------------------------
    {"id": 27, "name": "budweiser 330ml", "price": 10, "category": "long neck"},
    {"id": 28, "name": "corona extra 330ml", "price": 12, "category": "long neck"},
    {"id": 29, "name": "heineken 0.0 330ml", "price": 10, "category": "long neck"},
    {"id": 30, "name": "heineken p.m lager 330ml", "price": 10, "category": "long neck"},
    {"id": 31, "name": "stella artois 330ml", "price": 10, "category": "long neck"},
    {"id": 32, "name": "draft vinho 600ml", "price": 14, "category": "long neck"},
    {"id": 33, "name": "51 ice", "price": 10, "category": "long neck"},
    {"id": 34, "name": "smirnoff ice 12s", "price": 12, "category": "long neck"},
    # ---------------------------------------------
    {"id": 35, "name": "passaport/energético 2 litros", "price": 90, "category": "combo whiskey"},
    {"id": 36, "name": "passaport/energético red bull", "price": 108, "category": "combo whiskey"},
    {"id": 37, "name": "white horse/energético 2 litros", "price": 140, "category": "combo whiskey"},
    {"id": 38, "name": "white horse/energético red bull", "price": 158, "category": "combo whiskey"},
    {"id": 39, "name": "jack daniels/energético 2 litros", "price": 210, "category": "combo whiskey"},
    {"id": 40, "name": "jack daniels/energético red bull", "price": 228, "category": "combo whiskey"},
    {"id": 41, "name": "jack honey/energético 2 litros", "price": 210, "category": "combo whiskey"},
    {"id": 42, "name": "jack honey/energético red bull", "price": 228, "category": "combo whiskey"},
    {"id": 43, "name": "jack maça verde/energético 2 litros", "price": 210, "category": "combo whiskey"},
    {"id": 44, "name": "jack maça verde/energético red bull", "price": 228, "category": "combo whiskey"},
    {"id": 45, "name": "red label/energético 2 litros", "price": 210, "category": "combo whiskey"},
    {"id": 46, "name": "red label/energético red bull", "price": 228, "category": "combo whiskey"},
    # ---------------------------------------------
    {"id": 47, "name": "eternity/energético 2 litros", "price": 70, "category": "combo gin"},
    {"id": 48, "name": "eternity/energético red bull", "price": 98, "category": "combo gin"},
    {"id": 49, "name": "evo gin/energético 2 litros", "price": 60, "category": "combo gin"},
    {"id": 50, "name": "evo gin/energético red bull", "price": 93, "category": "combo gin"},
    # ---------------------------------------------
    {"id": 51, "name": "velho barreiro", "price": 4, "category": "doses"},
    {"id": 52, "name": "pinga 51", "price": 4, "category": "doses"},
    {"id": 53, "name": "Cavalo branco", "price": 12, "category": "doses"},
    {"id": 54, "name": "campari", "price": 12, "category": "doses"},
    {"id": 55, "name": "alambique", "price": 4, "category": "doses"},
    {"id": 56, "name": "são francisco", "price": 6, "category": "doses"},
    {"id": 57, "name": "dreher", "price": 5, "category": "doses"},
    {"id": 58, "name": "canelinha", "price": 5, "category": "doses"},
    {"id": 59, "name": "jurupinga", "price": 8, "category": "doses"},
    {"id": 60, "name": "catuaba", "price": 6, "category": "doses"},
    {"id": 61, "name": "paratudo", "price": 5, "category": "doses"},
    # ---------------------------------------------
    {"id": 62, "name": "cavalo branco", "price": 30, "category": "copão"},
    {"id": 63, "name": "chanceller", "price": 20, "category": "copão"},
    {"id": 64, "name": "jack daniels", "price": 40, "category": "copão"},
    {"id": 65, "name": "Jack daniels maça verde", "price": 40, "category": "copão"},
    {"id": 66, "name": "Jack daniels honey", "price": 40, "category": "copão"},
    {"id": 67, "name": "Red label", "price": 30, "category": "copão"},
    {"id": 68, "name": "jack daniels maça verde", "price": 40, "category": "copão"},
    {"id": 69, "name": "jack daniels honey", "price": 40, "category": "copão"},
    {"id": 70, "name": "Red Label", "price": 30, "category": "copão"},
    {"id": 71, "name": "evo gim morango", "price": 25, "category": "copão"},
    {"id": 72, "name": "evo gim melancia", "price": 25, "category": "copão"},
    {"id": 73, "name": "evo gin maça verde", "price": 25, "category": "copão"},
    # ---------------------------------------------
    {"id": 74, "name": "chanceceller", "price": 35, "category": "whiskeys/licores/vodkas garrafa"},
    {"id": 75, "name": "passaport", "price": 60, "category": "whiskeys/licores/vodkas garrafa"},
    {"id": 76, "name": "red label", "price": 120, "category": "whiskeys/licores/vodkas garrafa"},
    {"id": 77, "name": "white horse 500ml", "price": 60, "category": "whiskeys/licores/vodkas garrafa"},
    {"id": 78, "name": "white horse 1 lt", "price": 110, "category": "whiskeys/licores/vodkas garrafa"},
    {"id": 79, "name": "Jack Daniels Honey", "price": 180, "category": "whiskeys/licores/vodkas garrafa"},
    {"id": 80, "name": "jack daniels tradicional", "price": 180, "category": "whiskeys/licores/vodkas garrafa"},
    {"id": 81, "name": "licor ballena", "price": 150, "category": "whiskeys/licores/vodkas garrafa"},
    {"id": 82, "name": "licor 43", "price": 160, "category": "whiskeys/licores/vodkas garrafa"},
    {"id": 83, "name": "licor chocolate", "price": 180, "category": "whiskeys/licores/vodkas garrafa"},
    {"id": 84, "name": "vodka smirnoff", "price": 65, "category": "whiskeys/licores/vodkas garrafa"},
    {"id": 85, "name": "vodka sky", "price": 65, "category": "whiskeys/licores/vodkas garrafa"},
    {"id": 86, "name": "vodka askov limao", "price": 30, "category": "whiskeys/licores/vodkas garrafa"},
    {"id": 87, "name": "vodka askov maracuja", "price": 30, "category": "whiskeys/licores/vodkas garrafa"},
    # ---------------------------------------------
    {"id": 88, "name": "theros gin kit+copo", "price": 70, "category": "gin"},
    {"id": 89, "name": "eternity tropical", "price": 30, "category": "gin"},
    {"id": 90, "name": "eternity maça verde", "price": 30, "category": "gin"},
    {"id": 91, "name": "eternity melancia", "price": 30, "category": "gin"},
    {"id": 92, "name": "evo gin melancia", "price": 25, "category": "gin"},
    {"id": 93, "name": "evo gin morango", "price": 25, "category": "gin"},
    {"id": 94, "name": "Evo gin maça verde", "price": 25, "category": "gin"},
    # ---------------------------------------------
    {"id": 95, "name": "domec", "price": 60.00, "category": "destilados"},
    {"id": 96, "name": "Campari", "price": 80.00, "category": "destilados"},
    {"id": 97, "name": "montila", "price": 45.00, "category": "destilados"},
    {"id": 98, "name": "Vodka askov limao", "price": 40.00, "category": "destilados"},
    {"id": 99, "name": "Vodka askov maracuja", "price": 40.00, "category": "destilados"},
    {"id": 100, "name": "baianinha maracuja", "price": 10.00, "category": "destilados"},
    {"id": 101, "name": "pitu lata", "price": 10.00, "category": "destilados"},
    {"id": 102, "name": "alba com mel 1 lt", "price": 30.00, "category": "destilados"},
    {"id": 103, "name": "alba com mel 500", "price": 15.00, "category": "destilados"},
    {"id": 104, "name": "corote sabores", "price": 10.00, "category": "destilados"},
    {"id": 105, "name": "catuaba 300ml", "price": 7.00, "category": "destilados"},
    {"id": 106, "name": "canelinha 300", "price": 8.00, "category": "destilados"},
    {"id": 107, "name": "cachaça sagatiba", "price": 45.00, "category": "destilados"},
    {"id": 108, "name": "saque seco 600 ml", "price": 36.00, "category": "destilados"},
    {"id": 109, "name": "São francisco", "price": 50.00, "category": "destilados"},
    {"id": 110, "name": "Pinga 51", "price": 20.00, "category": "destilados"},
    {"id": 111, "name": "Velho barreiro", "price": 24.00, "category": "destilados"},
    {"id": 112, "name": "velho barreiro limao", "price": 28.00, "category": "destilados"},
    # ---------------------------------------------
    {"id": 113, "name": "dunhill", "price": 13.75, "category": "tabacaria"},
    {"id": 114, "name": "chesterfield", "price": 9.00, "category": "tabacaria"},
    {"id": 115, "name": "rothmans", "price": 9.50, "category": "tabacaria"},
    {"id": 116, "name": "marlboro", "price": 10.00, "category": "tabacaria"},
    {"id": 117, "name": "essencia ziggy", "price": 15.00, "category": "tabacaria"},
    {"id": 118, "name": "fumo", "price": 5.00, "category": "tabacaria"},
    {"id": 119, "name": "paieiro autentico", "price": 10.00, "category": "tabacaria"},
    {"id": 120, "name": "paieiro flor do norte", "price": 10.00, "category": "tabacaria"},
    {"id": 121, "name": "fosforo", "price": 1.00, "category": "tabacaria"},
    {"id": 122, "name": "cigarro solto", "price": 0.50, "category": "tabacaria"},
    {"id": 123, "name": "seda", "price": 5.00, "category": "tabacaria"},
    {"id": 124, "name": "seda solta", "price": 0.50, "category": "tabacaria"},
    {"id": 125, "name": "aluminio solto", "price": 0.50, "category": "tabacaria"},
    {"id": 126, "name": "carvao narguile d'coco", "price": 15.00, "category": "tabacaria"},
    {"id": 127, "name": "carvao narguile unidade", "price": 1.50, "category": "tabacaria"},
    # ---------------------------------------------
    {"id": 128, "name": "itaipava 350ml com 12", "price": 38.00, "category": "fardos de cerveja"},
    {"id": 129, "name": "skol 350ml com 12", "price": 55, "category": "fardos de cerveja"},
    {"id": 130, "name": "skol 269ml com 15", "price": 55.00, "category": "fardos de cerveja"},
    {"id": 131, "name": "petra 269ml com 12", "price": 30.00, "category": "fardos de cerveja"},
    {"id": 132, "name": "imperio 269ml com 12", "price": 48, "category": "fardos de cerveja"},
    {"id": 133, "name": "imperio 350ml com 12", "price": 55.00, "category": "fardos de cerveja"},
    {"id": 134, "name": "original 269ml com 8", "price": 38.00, "category": "fardos de cerveja"},
    {"id": 135, "name": "original 350ml com 12", "price": 60.00, "category": "fardos de cerveja"},
    {"id": 136, "name": "amstel 269ml com 12", "price": 40.00, "category": "fardos de cerveja"},
    {"id": 137, "name": "amstel 350 ml com 12", "price": 48.00, "category": "fardos de cerveja"},
    {"id": 138, "name": "heineken 350 com 12", "price": 68.00, "category": "fardos de cerveja"},
    {"id": 139, "name": "heineken 260 com 8", "price": 40.00, "category": "fardos de cerveja"},
    {"id": 140, "name": "brahma duplo malte 269 com 15", "price": 48.00, "category": "fardos de cerveja"},
    # ---------------------------------------------
    {"id": 141, "name": "torcida", "price": 4.00, "category": "salgadinhos"},
    {"id": 142, "name": "batata caseira", "price": 25.00, "category": "salgadinhos"},
    {"id": 143, "name": "fritop", "price": 10.00, "category": "salgadinhos"},
    {"id": 144, "name": "pringles", "price": 18.00, "category": "salgadinhos"},
    # ---------------------------------------------
    {"id": 145, "name": "saco de gelo", "price": 15.00, "category": "gelos"},
    {"id": 146, "name": "gelo de coco e outros sabores", "price": 4.00, "category": "gelos"}
]
